/*
 clipboard.js v1.7.1
 https://zenorocha.github.io/clipboard.js

 Licensed MIT © Zeno Rocha
*/
(function(n){"object"===typeof exports&&"undefined"!==typeof module?module.exports=n():"function"===typeof define&&define.amd?define([],n):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).Clipboard=n()})(function(){return function a(d,f,h){function b(e,l){if(!f[e]){if(!d[e]){var c="function"==typeof require&&require;if(!l&&c)return c(e,!0);if(g)return g(e,!0);c=Error("Cannot find module '"+e+"'");throw c.code="MODULE_NOT_FOUND",c;}c=f[e]=
{exports:{}};d[e][0].call(c.exports,function(a){var c=d[e][1][a];return b(c?c:a)},c,c.exports,a,d,f,h)}return f[e].exports}for(var g="function"==typeof require&&require,k=0;k<h.length;k++)b(h[k]);return b}({1:[function(d,f,h){"undefined"===typeof Element||Element.prototype.matches||(d=Element.prototype,d.matches=d.matchesSelector||d.mozMatchesSelector||d.msMatchesSelector||d.oMatchesSelector||d.webkitMatchesSelector);f.exports=function(a,b){for(;a&&9!==a.nodeType;){if("function"===typeof a.matches&&
a.matches(b))return a;a=a.parentNode}}},{}],2:[function(d,f,h){function a(a,k,e,l){return function(c){c.delegateTarget=b(c.target,k);c.delegateTarget&&l.call(a,c)}}var b=d("./closest");f.exports=function(b,k,e,l,c){var m=a.apply(this,arguments);b.addEventListener(e,m,c);return{destroy:function(){b.removeEventListener(e,m,c)}}}},{"./closest":1}],3:[function(d,f,h){h.node=function(a){return void 0!==a&&a instanceof HTMLElement&&1===a.nodeType};h.nodeList=function(a){var b=Object.prototype.toString.call(a);
return void 0!==a&&("[object NodeList]"===b||"[object HTMLCollection]"===b)&&"length"in a&&(0===a.length||h.node(a[0]))};h.string=function(a){return"string"===typeof a||a instanceof String};h.fn=function(a){return"[object Function]"===Object.prototype.toString.call(a)}},{}],4:[function(d,f,h){function a(a,b,c){a.addEventListener(b,c);return{destroy:function(){a.removeEventListener(b,c)}}}function b(a,b,c){Array.prototype.forEach.call(a,function(a){a.addEventListener(b,c)});return{destroy:function(){Array.prototype.forEach.call(a,
function(a){a.removeEventListener(b,c)})}}}var g=d("./is"),k=d("delegate");f.exports=function(e,d,c){if(!e&&!d&&!c)throw Error("Missing required arguments");if(!g.string(d))throw new TypeError("Second argument must be a String");if(!g.fn(c))throw new TypeError("Third argument must be a Function");if(g.node(e))return a(e,d,c);if(g.nodeList(e))return b(e,d,c);if(g.string(e))return k(document.body,e,d,c);throw new TypeError("First argument must be a String, HTMLElement, HTMLCollection, or NodeList");
}},{"./is":3,delegate:2}],5:[function(d,f,h){f.exports=function(a){if("SELECT"===a.nodeName)a.focus(),a=a.value;else if("INPUT"===a.nodeName||"TEXTAREA"===a.nodeName){var b=a.hasAttribute("readonly");b||a.setAttribute("readonly","");a.select();a.setSelectionRange(0,a.value.length);b||a.removeAttribute("readonly");a=a.value}else{a.hasAttribute("contenteditable")&&a.focus();b=window.getSelection();var g=document.createRange();g.selectNodeContents(a);b.removeAllRanges();b.addRange(g);a=b.toString()}return a}},
{}],6:[function(d,f,h){function a(){}a.prototype={on:function(a,g,d){var b=this.e||(this.e={});(b[a]||(b[a]=[])).push({fn:g,ctx:d});return this},once:function(a,d,k){function b(){g.off(a,b);d.apply(k,arguments)}var g=this;b._=d;return this.on(a,b,k)},emit:function(a){var b=[].slice.call(arguments,1),d=((this.e||(this.e={}))[a]||[]).slice(),e=0,f=d.length;for(e;e<f;e++)d[e].fn.apply(d[e].ctx,b);return this},off:function(a,d){var b=this.e||(this.e={}),e=b[a],g=[];if(e&&d)for(var c=0,m=e.length;c<m;c++)e[c].fn!==
d&&e[c].fn._!==d&&g.push(e[c]);g.length?b[a]=g:delete b[a];return this}};f.exports=a},{}],7:[function(d,f,h){(function(a,b){if("undefined"!==typeof h)b(f,d("select"));else{var g={exports:{}};b(g,a.select);a.clipboardAction=g.exports}})(this,function(a,b){var d=b&&b.__esModule?b:{"default":b},f="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},e=
function(){function a(a,b){for(var d=0;d<b.length;d++){var c=b[d];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(a,c.key,c)}}return function(b,c,d){c&&a(b.prototype,c);d&&a(b,d);return b}}(),h=function(){function a(b){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");this.resolveOptions(b);this.initSelection()}e(a,[{key:"resolveOptions",value:function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};
this.action=a.action;this.container=a.container;this.emitter=a.emitter;this.target=a.target;this.text=a.text;this.trigger=a.trigger;this.selectedText=""}},{key:"initSelection",value:function(){this.text?this.selectFake():this.target&&this.selectTarget()}},{key:"selectFake",value:function(){var a=this,b="rtl"==document.documentElement.getAttribute("dir");this.removeFake();this.fakeHandlerCallback=function(){return a.removeFake()};this.fakeHandler=this.container.addEventListener("click",this.fakeHandlerCallback)||
!0;this.fakeElem=document.createElement("textarea");this.fakeElem.style.fontSize="12pt";this.fakeElem.style.border="0";this.fakeElem.style.padding="0";this.fakeElem.style.margin="0";this.fakeElem.style.position="absolute";this.fakeElem.style[b?"right":"left"]="-9999px";this.fakeElem.style.top=(window.pageYOffset||document.documentElement.scrollTop)+"px";this.fakeElem.setAttribute("readonly","");this.fakeElem.value=this.text;this.container.appendChild(this.fakeElem);this.selectedText=(0,d["default"])(this.fakeElem);
this.copyText()}},{key:"removeFake",value:function(){this.fakeHandler&&(this.container.removeEventListener("click",this.fakeHandlerCallback),this.fakeHandlerCallback=this.fakeHandler=null);this.fakeElem&&(this.container.removeChild(this.fakeElem),this.fakeElem=null)}},{key:"selectTarget",value:function(){this.selectedText=(0,d["default"])(this.target);this.copyText()}},{key:"copyText",value:function(){var a=void 0;try{a=document.execCommand(this.action)}catch(r){a=!1}this.handleResult(a)}},{key:"handleResult",
value:function(a){this.emitter.emit(a?"success":"error",{action:this.action,text:this.selectedText,trigger:this.trigger,clearSelection:this.clearSelection.bind(this)})}},{key:"clearSelection",value:function(){this.trigger&&this.trigger.focus();window.getSelection().removeAllRanges()}},{key:"destroy",value:function(){this.removeFake()}},{key:"action",set:function(){this._action=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"copy";if("copy"!==this._action&&"cut"!==this._action)throw Error('Invalid "action" value, use either "copy" or "cut"');
},get:function(){return this._action}},{key:"target",set:function(a){if(void 0!==a)if(a&&"object"===("undefined"===typeof a?"undefined":f(a))&&1===a.nodeType){if("copy"===this.action&&a.hasAttribute("disabled"))throw Error('Invalid "target" attribute. Please use "readonly" instead of "disabled" attribute');if("cut"===this.action&&(a.hasAttribute("readonly")||a.hasAttribute("disabled")))throw Error('Invalid "target" attribute. You can\'t cut text from elements with "readonly" or "disabled" attributes');
this._target=a}else throw Error('Invalid "target" value, use a valid Element');},get:function(){return this._target}}]);return a}();a.exports=h})},{select:5}],8:[function(d,f,h){(function(a,b){if("undefined"!==typeof h)b(f,d("./clipboard-action"),d("tiny-emitter"),d("good-listener"));else{var g={exports:{}};b(g,a.clipboardAction,a.tinyEmitter,a.goodListener);a.clipboard=g.exports}})(this,function(a,b,d,f){function e(a){return a&&a.__esModule?a:{"default":a}}function g(a,b){if("function"!==typeof b&&
null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)}function c(a,b){var d="data-clipboard-"+a;if(b.hasAttribute(d))return b.getAttribute(d)}var h=e(b);b=e(d);var k=e(f),p="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&
"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},q=function(){function a(a,b){for(var d=0;d<b.length;d++){var c=b[d];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(a,c.key,c)}}return function(b,d,c){d&&a(b.prototype,d);c&&a(b,c);return b}}();f=function(a){function b(a,d){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var c=(b.__proto__||Object.getPrototypeOf(b)).call(this);
if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");c=!c||"object"!==typeof c&&"function"!==typeof c?this:c;c.resolveOptions(d);c.listenClick(a);return c}g(b,a);q(b,[{key:"resolveOptions",value:function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};this.action="function"===typeof a.action?a.action:this.defaultAction;this.target="function"===typeof a.target?a.target:this.defaultTarget;this.text="function"===typeof a.text?a.text:this.defaultText;
this.container="object"===p(a.container)?a.container:document.body}},{key:"listenClick",value:function(a){var b=this;this.listener=(0,k["default"])(a,"click",function(a){return b.onClick(a)})}},{key:"onClick",value:function(a){a=a.delegateTarget||a.currentTarget;this.clipboardAction&&(this.clipboardAction=null);this.clipboardAction=new h["default"]({action:this.action(a),target:this.target(a),text:this.text(a),container:this.container,trigger:a,emitter:this})}},{key:"defaultAction",value:function(a){return c("action",
a)}},{key:"defaultTarget",value:function(a){if(a=c("target",a))return document.querySelector(a)}},{key:"defaultText",value:function(a){return c("text",a)}},{key:"destroy",value:function(){this.listener.destroy();this.clipboardAction&&(this.clipboardAction.destroy(),this.clipboardAction=null)}}],[{key:"isSupported",value:function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:["copy","cut"],b=!!document.queryCommandSupported;("string"===typeof a?[a]:a).forEach(function(a){b=b&&!!document.queryCommandSupported(a)});
return b}}]);return b}(b["default"]);a.exports=f})},{"./clipboard-action":7,"good-listener":4,"tiny-emitter":6}]},{},[8])(8)});